name: Integration tests

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "main"

jobs:
  npm_update_sync_node_14:
    runs-on: ubuntu-latest
    name: Update npm packages and sync package.json with nodejs 14 npm 6
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Update package.json
        id: update
        uses: tjololo/npm-package-update-sync@main
        with:
          recursive: false
          comment-updated: true
          root-folder: __tests__/it/package-lock-v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "PR from integration tests package-lock v1"
          branch: "tests/npm-updates-integration-v1"
          body: ${{ steps.update.outputs.body }}
          labels: dependencies
  npm_update_sync_ndoe_16:
    runs-on: ubuntu-latest
    name: Update npm packages and sync package.json with nodejs 16 npm 7
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Update package.json
        id: update
        uses: tjololo/npm-package-update-sync@main
        with:
          recursive: false
          comment-updated: true
          root-folder: __tests__/it/package-lock-v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "PR from integration tests package-lock v2"
          branch: "tests/npm-updates-integration-v2"
          body: ${{ steps.update.outputs.body }}
          labels: dependencies