name: Test
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm install
      - name: run jest test
        run: npm run test