name: Test
on:
  pull_request:
    branches: [main]

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm install
      - name: run jest test
        run: npm run test
      - name: SonarCloud Scan
        if: matrix.node == '16' && 
            github.repository_owner == 'tjololo' &&
            (github.event_name != 'pull_request' && github.event.repository.fork == false) ||
            (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: test npm build
        run: npm run build
